### ISSUE TITLE
抖音好像改规则了socket动了

### ISSUE THREAD

**Issue by QingyuanSTUDIO** [ToxicStar8/DouYinLiveFetchToUnity#2]

**Comment by luckyyjian** [comment]
只需要改UIMainMenu.cs里的wsUrl就行了
var wsUrl = $"wss://webcast5-ws-web-lq.douyin.com/webcast/im/push/v2/?app_name=douyin_web&version_code=180800&webcast_sdk_version=1.0.14-beta.0&update_version_code=1.0.14-beta.0&compress=gzip&device_platform=web&cookie_enabled=true&screen_width=1920&screen_height=1080&browser_language=zh-CN&browser_platform=Win32&browser_name=Mozilla&browser_version=5.0%20(Windows%20NT%2010.0;%20Win64;%20x64)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/126.0.0.0%20Safari/537.36%20Edg/126.0.0.0&browser_online=true&tz_name=Asia/Hong_Kong&cursor=t-1719993875534_r-1_d-1_u-1_fh-7387314462967501851&internal_ext=internal_src:dim|wss_push_room_id:{_liveRoomId}|wss_push_did:7385067917925369394|first_req_ms:1719993875443|fetch_time:1719993875534|seq:1|wss_info:0-1719993875534-0-0|wrds_v:7387317433855380000&host=https://live.douyin.com&aid=6383&live_id=1&did_rule=3&endpoint=live_pc&support_wrds=1&user_unique_id=7385067917925369394&im_path=/webcast/im/fetch/&identity=audience&need_persist_msg_count=15&insert_task_id=&live_reason=&room_id={_liveRoomId}&heartbeatDuration=0&signature=60REnIok7wigVa+b";

**Comment by QingyuanSTUDIO** [comment]
![image](https://github.com/ToxicStar8/douyin-live-unity/assets/92435310/f1681512-46db-461d-bb82-f531ffb33a7f)
？

**Comment by QingyuanSTUDIO** [comment]
按照您的方法做了，但是还是会出现websocket直接关闭

**Comment by ToxicStar8** [comment]
> _No description provided._
 
更新了，拉取一下新的提交c78ffb4d即可

**Comment by QingyuanSTUDIO** [comment]
好了 谢谢，问题解决了，但是直播间如果弹幕数量过多会导致断联。可能因为我ip在新加坡
